# generated by datamodel-codegen:
#   filename:  competitor.json
#   timestamp: 2026-03-26T11:47:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, Field


class Format(Enum):
    cottage_village = 'cottage_village'
    country_club = 'country_club'
    eco_hotel = 'eco_hotel'
    resort = 'resort'
    mixed = 'mixed'


class PricePerNightRub(BaseModel):
    min: Annotated[int, Field(ge=0)]
    max: Annotated[int, Field(ge=0)]


class OccupancyEstimate(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'
    unknown = 'unknown'


class CompetitorProfile(BaseModel):
    name: Annotated[str, Field(description='Название объекта')]
    url: Annotated[
        AnyUrl | None, Field(description='Сайт или страница бронирования')
    ] = None
    location: Annotated[str, Field(description='Населённый пункт / район')]
    distance_spb_km: Annotated[
        float | None, Field(description='Расстояние от СПб, км', ge=0.0)
    ] = None
    format: Annotated[Format, Field(description='Формат объекта')]
    price_per_night_rub: PricePerNightRub | None = None
    cottage_count: Annotated[
        int | None, Field(description='Количество коттеджей / номеров', ge=1)
    ] = None
    infrastructure: Annotated[
        list[str] | None,
        Field(description="Перечень инфраструктуры: ['баня', 'детская_площадка', ...]"),
    ] = None
    rating: Annotated[
        float | None,
        Field(description='Средний рейтинг на агрегаторах', ge=0.0, le=5.0),
    ] = None
    reviews_count: Annotated[int | None, Field(ge=0)] = None
    occupancy_estimate: OccupancyEstimate | None = None
    strengths: list[str] | None = None
    weaknesses: list[str] | None = None
    is_failed_case: Annotated[bool, Field(description='Является ли неудачным кейсом')]
    failure_reasons: Annotated[
        list[str] | None,
        Field(description='Причины неудачи (только если is_failed_case=true)'),
    ] = None
