# generated by datamodel-codegen:
#   filename:  customer_segment.json
#   timestamp: 2026-03-26T11:47:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class SegmentId(Enum):
    investor = 'investor'
    buyer = 'buyer'
    renter = 'renter'


class IncomeLevel(Enum):
    medium = 'medium'
    above_average = 'above_average'
    high = 'high'


class WillingnessToPayRub(BaseModel):
    min: Annotated[int, Field(ge=0)]
    max: Annotated[int, Field(ge=0)]


class AudienceSegment(BaseModel):
    segment_id: Annotated[
        SegmentId,
        Field(
            description='investor=инвестор в строительство, buyer=покупатель дома, renter=арендатор'
        ),
    ]
    name: Annotated[str, Field(description='Название сегмента')]
    age_range: Annotated[
        list[int] | None,
        Field(description='Возрастной диапазон [min, max]', max_length=2, min_length=2),
    ] = None
    income_level: Annotated[IncomeLevel | None, Field(description='Уровень дохода')] = (
        None
    )
    geography: Annotated[
        list[str] | None,
        Field(description='Географические характеристики (СПб, Москва, ...)'),
    ] = None
    motivation: Annotated[list[str], Field(description='Ключевые мотивы')]
    decision_criteria: Annotated[
        list[str], Field(description='Критерии выбора объекта')
    ]
    barriers: Annotated[list[str], Field(description='Барьеры и возражения')]
    preferred_channels: Annotated[
        list[str] | None, Field(description='Каналы коммуникации (VK, Telegram, ...)')
    ] = None
    willingness_to_pay_rub: Annotated[
        WillingnessToPayRub | None,
        Field(description='Готовность платить, руб (аренда/ночь или покупка)'),
    ] = None
