# generated by datamodel-codegen:
#   filename:  location.json
#   timestamp: 2026-03-26T11:42:27+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class LocationScore(BaseModel):
    name: Annotated[str, Field(description='Название локации')]
    distance_spb_min: Annotated[
        int, Field(description='Время в пути от СПб, мин', ge=0)
    ]
    land_price_rub_sotka: Annotated[
        int | None, Field(description='Стоимость земли, руб/сотка', ge=0)
    ] = None
    competition_density: Annotated[
        int | None, Field(description='Кол-во конкурентов в радиусе 10 км', ge=0)
    ] = None
    water_proximity_km: Annotated[
        float | None, Field(description='Расстояние до воды, км', ge=0.0)
    ] = None
    unique_attraction: Annotated[
        str | None,
        Field(description='Уникальный аттрактор (серфинг, горнолыжка и т.д.)'),
    ] = None
    infrastructure_score: Annotated[
        int, Field(description='Балл инфраструктуры района', ge=1, le=10)
    ]
    legal_restrictions: Annotated[
        bool, Field(description='Наличие правовых ограничений')
    ]
    legal_notes: Annotated[
        str | None, Field(description='Комментарий по правовым ограничениям')
    ] = None
    total_score: Annotated[
        float | None, Field(description='Итоговый балл (GLM/CatBoost)')
    ] = None
    recommendation: Annotated[
        str | None, Field(description='Итоговая рекомендация по локации')
    ] = None
