# generated by datamodel-codegen:
#   filename:  research_report.json
#   timestamp: 2026-03-26T11:47:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class GrowthTrend(Enum):
    growing = 'growing'
    stable = 'stable'
    declining = 'declining'


class MarketOverview(BaseModel):
    summary: str
    market_volume_rub: Annotated[
        int, Field(description='Объём рынка, руб/год (оценка)')
    ]
    growth_trend: Annotated[GrowthTrend, Field(description='Динамика рынка')]
    seasonality_notes: str
    key_trends: list[str]
    years_covered: Annotated[
        list[int] | None, Field(description='Годы анализа (последние 3–5 лет)')
    ] = None


class TargetSegmentId(Enum):
    investor = 'investor'
    buyer = 'buyer'
    renter = 'renter'


class ConceptVariant(BaseModel):
    name: str
    positioning: str
    usp: Annotated[str, Field(description='Уникальное торговое предложение')]
    architectural_notes: str | None = None
    target_segment_ids: list[TargetSegmentId]
    feasibility_score: Annotated[int, Field(ge=1, le=10)]
    pros: list[str] | None = None
    cons: list[str] | None = None


class Expert(BaseModel):
    name: str
    project: str
    key_topics: list[str]


class ExpertInterviewGuide(BaseModel):
    experts: list[Expert]
    questions: list[str]


class Swot(BaseModel):
    strengths: list[str]
    weaknesses: list[str]
    opportunities: list[str]
    threats: list[str]


class Format(Enum):
    cottage_village = 'cottage_village'
    country_club = 'country_club'
    eco_hotel = 'eco_hotel'
    resort = 'resort'
    mixed = 'mixed'


class PricePerNightRub(BaseModel):
    min: Annotated[int, Field(ge=0)]
    max: Annotated[int, Field(ge=0)]


class OccupancyEstimate(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'
    unknown = 'unknown'


class Competitor(BaseModel):
    name: Annotated[str, Field(description='Название объекта')]
    url: Annotated[
        AnyUrl | None, Field(description='Сайт или страница бронирования')
    ] = None
    location: Annotated[str, Field(description='Населённый пункт / район')]
    distance_spb_km: Annotated[
        float | None, Field(description='Расстояние от СПб, км', ge=0.0)
    ] = None
    format: Annotated[Format, Field(description='Формат объекта')]
    price_per_night_rub: PricePerNightRub | None = None
    cottage_count: Annotated[
        int | None, Field(description='Количество коттеджей / номеров', ge=1)
    ] = None
    infrastructure: Annotated[
        list[str] | None,
        Field(description="Перечень инфраструктуры: ['баня', 'детская_площадка', ...]"),
    ] = None
    rating: Annotated[
        float | None,
        Field(description='Средний рейтинг на агрегаторах', ge=0.0, le=5.0),
    ] = None
    reviews_count: Annotated[int | None, Field(ge=0)] = None
    occupancy_estimate: OccupancyEstimate | None = None
    strengths: list[str] | None = None
    weaknesses: list[str] | None = None
    is_failed_case: Annotated[bool, Field(description='Является ли неудачным кейсом')]
    failure_reasons: Annotated[
        list[str] | None,
        Field(description='Причины неудачи (только если is_failed_case=true)'),
    ] = None


class Location(BaseModel):
    name: Annotated[str, Field(description='Название локации')]
    distance_spb_min: Annotated[
        int, Field(description='Время в пути от СПб, мин', ge=0)
    ]
    land_price_rub_sotka: Annotated[
        int | None, Field(description='Стоимость земли, руб/сотка', ge=0)
    ] = None
    competition_density: Annotated[
        int | None, Field(description='Кол-во конкурентов в радиусе 10 км', ge=0)
    ] = None
    water_proximity_km: Annotated[
        float | None, Field(description='Расстояние до воды, км', ge=0.0)
    ] = None
    unique_attraction: Annotated[
        str | None,
        Field(description='Уникальный аттрактор (серфинг, горнолыжка и т.д.)'),
    ] = None
    infrastructure_score: Annotated[
        int, Field(description='Балл инфраструктуры района', ge=1, le=10)
    ]
    legal_restrictions: Annotated[
        bool, Field(description='Наличие правовых ограничений')
    ]
    legal_notes: Annotated[
        str | None, Field(description='Комментарий по правовым ограничениям')
    ] = None
    total_score: Annotated[
        float | None, Field(description='Итоговый балл (GLM/CatBoost)')
    ] = None
    recommendation: Annotated[
        str | None, Field(description='Итоговая рекомендация по локации')
    ] = None


class SegmentId(Enum):
    investor = 'investor'
    buyer = 'buyer'
    renter = 'renter'


class IncomeLevel(Enum):
    medium = 'medium'
    above_average = 'above_average'
    high = 'high'


class WillingnessToPayRub(BaseModel):
    min: Annotated[int, Field(ge=0)]
    max: Annotated[int, Field(ge=0)]


class CustomerSegment(BaseModel):
    segment_id: Annotated[
        SegmentId,
        Field(
            description='investor=инвестор в строительство, buyer=покупатель дома, renter=арендатор'
        ),
    ]
    name: Annotated[str, Field(description='Название сегмента')]
    age_range: Annotated[
        list[int] | None,
        Field(description='Возрастной диапазон [min, max]', max_length=2, min_length=2),
    ] = None
    income_level: Annotated[IncomeLevel | None, Field(description='Уровень дохода')] = (
        None
    )
    geography: Annotated[
        list[str] | None,
        Field(description='Географические характеристики (СПб, Москва, ...)'),
    ] = None
    motivation: Annotated[list[str], Field(description='Ключевые мотивы')]
    decision_criteria: Annotated[
        list[str], Field(description='Критерии выбора объекта')
    ]
    barriers: Annotated[list[str], Field(description='Барьеры и возражения')]
    preferred_channels: Annotated[
        list[str] | None, Field(description='Каналы коммуникации (VK, Telegram, ...)')
    ] = None
    willingness_to_pay_rub: Annotated[
        WillingnessToPayRub | None,
        Field(description='Готовность платить, руб (аренда/ночь или покупка)'),
    ] = None


class ResearchReport(BaseModel):
    title: str
    created_at: AwareDatetime
    market_overview: MarketOverview
    competitors: Annotated[list[Competitor], Field(max_length=15, min_length=10)]
    failed_cases: Annotated[list[Competitor] | None, Field(min_length=2)] = None
    locations: Annotated[list[Location], Field(max_length=4, min_length=3)]
    audience_segments: Annotated[
        list[CustomerSegment], Field(max_length=3, min_length=3)
    ]
    concept_variants: Annotated[
        list[ConceptVariant] | None, Field(max_length=3, min_length=2)
    ] = None
    expert_interview_guide: ExpertInterviewGuide | None = None
    swot: Swot
    conclusions: Annotated[
        str, Field(description='Итоговые выводы и рекомендации по проекту')
    ]
